FROM python:3.11 as myapi

WORKDIR /app

COPY ./jds_dashboard/fastapi_app/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./jds_dashboard/fastapi_app /app

CMD ["fastapi", "run", "main.py", "--port", "80"]