FROM python:3.11 as mydash

WORKDIR /app

COPY ./jds_dashboard/dash_app/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./jds_dashboard/dash_app /app

CMD [ "python",  "app.py"]