version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    image: db:latest
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jds_data